[package]
name = "gonk-player"
version = "0.0.1"
edition = "2021"

authors = ["Bay"]
description = "Music playback library for gonk"
repository = "https://github.com/zX3no/gonk"
readme = "README.md"
license = "MIT"

[dependencies]
cpal = "0.13.5"
gonk-core = { version = "*", path = "../gonk-core" }
optick = "1.3.4"
rand = "0.8.5"
symphonia = { version = "0.5.0", features = ["aac", "mp3", "isomp4"] }
