[package]
name = "gonk-player"
version = "0.1.0"
edition = "2021"

authors = ["Bay"]
description = "Music playback library for gonk"
repository = "https://github.com/zX3no/gonk"
readme = "README.md"
license = "MIT"

[dependencies]
cpal = {git = "https://github.com/zX3no/cpal"}
symphonia = { version = "0.5.0", features = ["mp3", "isomp4", "alac", "aac"] }
gonk-database = {path = "../gonk-database"}

[target.'cfg(unix)'.dependencies]
gag = "1.0.0"